# Generated by Django 3.1.3 on 2020-11-20 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shiksha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=60)),
                ('contact_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('pincode', models.IntegerField(max_length=6)),
                ('isdcode', models.IntegerField(blank=True, default='91+')),
                ('phone_no', models.BigIntegerField(max_length=10)),
                ('consent', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collegeuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
