# Generated by Django 3.1.3 on 2020-11-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiksha', '0002_collegeuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clg_name', models.CharField(max_length=100)),
                ('clg_mail', models.EmailField(max_length=254)),
                ('clg_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('clg_contactno', models.BigIntegerField()),
                ('year', models.IntegerField()),
                ('nirf', models.IntegerField()),
                ('ownership', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='collegeuser',
            name='phone_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='collegeuser',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
