# Generated by Django 3.1.3 on 2020-11-21 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shiksha', '0003_auto_20201120_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('avg_sal', models.DecimalField(decimal_places=2, max_digits=9)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('clg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place', to='shiksha.college')),
            ],
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('clg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provide', to='shiksha.college')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(max_length=100)),
                ('programme', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=200)),
                ('number_seats', models.IntegerField()),
                ('fees', models.BigIntegerField()),
                ('duration', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('clg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='shiksha.college')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appform_link', models.URLField()),
                ('appform_fee', models.IntegerField()),
                ('submit_date', models.DateField()),
                ('entrance_exam', models.CharField(max_length=200)),
                ('clg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admits', to='shiksha.college')),
            ],
        ),
    ]
