# Generated by Django 3.1.3 on 2020-11-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiksha', '0004_admission_course_infrastructure_placement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='superuser'),
        ),
    ]
