# Generated by Django 3.1.3 on 2020-11-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiksha', '0005_auto_20201121_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='state',
            field=models.CharField(default='Tamilnadu', max_length=50),
        ),
        migrations.AddField(
            model_name='collegeuser',
            name='state',
            field=models.CharField(default='Tamilnadu', max_length=50),
        ),
    ]
