# Generated by Django 3.1.3 on 2020-11-22 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shiksha', '0006_auto_20201122_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegeuser',
            name='isdcode',
        ),
    ]
